### PR TITLE
Simplify CMakeLists.txt

### PR DESCRIPTION
**Pull request by ChrisThrasher**
I loved this simulator so I thought I'd contribute some simplifications to the top level CMakeLists.txt. I hope you appreciate it!

### CODE REVIEW

**Comment by IvanOrfanidi** [comment]
Hello everybody!
I would suggest leaving out " find_package(OpenGL)".
Yet it is looking for a library.
Can we remove "LANGUAGES CXX"?
Cmake is now able to define projects well.

**Comment by IvanOrfanidi** [comment]
Is the C++ 11 version required?
I would suggest raising it to 17.
Better so "set (CMAKE_CXX_STANDARD 17)"
than so
"set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 11)"
or
"" target_compile_features(${PROJECT_NAME} PRIVATE xxx_std_11)"

**Comment by ChrisThrasher** [comment]
> Hello everybody!
> 
> I would suggest leaving out " find_package(OpenGL)".
> 
> Yet it is looking for a library.
> 
> Can we remove "LANGUAGES CXX"?
> 
> Cmake is now able to define projects well.

I did remove 'find_package(OpenGL)'. 

'LANGUAGES CXX' is telling CMake to not bother finding a C compile since this project only uses C++. It's useful.

**Comment by ChrisThrasher** [comment]
@johnBuffer Are you able to take a look at this? Looks like most development is happening on branches ahead of `master` but this MR has very minimal conflicts with the latest work you're doing. Thanks!

**Comment by johnBuffer** [comment]
Thanks for this!

**Pull request merged**
